import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";

import "./globals.css";
import Script from "next/script";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <Script
            defer
            data-domain="languagestory.app"
            data-api="/p/api/event"
            src="/p/js/script.js"
          />
        </head>
        {children}
      </html>
    </ClerkProvider>
  );
}
