import { ClerkProvider } from "@clerk/nextjs";
import PlausibleProvider from "next-plausible";
import type { Metadata } from "next";

import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <PlausibleProvider domain="languagestory.app">
          {children}
        </PlausibleProvider>
      </html>
    </ClerkProvider>
  );
}
