name: Language Story

on:
  schedule:
    - cron: '0 13 * * *' # 8:00am EST
  workflow_dispatch:

jobs:
  language-story:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      
      - name: Install Dependencies
        run: npm install

      - name: Run Script
        run: npm run generate-story
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}

      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'